# Generated by Django 5.2 on 2025-04-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(max_length=50, unique=True)),
                ('OrderItemId', models.CharField(max_length=50)),
                ('QuantityOrdered', models.IntegerField()),
                ('ItemPrice', models.FloatField()),
                ('PromotionDiscount', models.FloatField()),
                ('total_sales', models.FloatField()),
                ('net_sale', models.FloatField()),
                ('region', models.CharField(max_length=1)),
            ],
        ),
    ]
